apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-website.fullname" . }}
  labels: {{ include "nginx-website.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       {{ .Values.service.port }};
      server_name  {{ .Values.nginx.serverName }};
      location / {
        root   {{ .Values.nginx.slashLocation.root }};
        index  {{ .Values.nginx.slashLocation.index }};
        autoindex {{ .Values.nginx.slashLocation.autoindex }};
        {{- if .Values.nginx.slashLocation.tryFiles }}
        try_files {{ .Values.nginx.slashLocation.tryFiles }};
        {{- end}}
      }
    }
