apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-site-frontend.fullname" . }}
  labels:
    {{- include "plugin-site-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: frontend
      protocol: TCP
      targetPort: frontend
      port: {{ .Values.frontend.port }}
  selector:
    {{- include "plugin-site-frontend.selectorLabels" . | nindent 4}}
