apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-httpd
  labels:
    app.kubernetes.io/name: httpd
    helm.sh/chart: httpd-1.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v2.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: httpd
    app.kubernetes.io/instance: RELEASE-NAME
