imageCredentials:
  enabled: false
  registry: https://index.docker.io/v1/ # DockerHub default
  username: someone
  password: sillyness
  email: someone@host.com
## Uncomment to set quotas
# quotas:
#   pods: 30
## uncomment to reuse an existing service account
# existingServiceAccount: jenkins-infra:jenkins-controller
## Uncomment to add groups for rbac access entries, see https://docs.aws.amazon.com/eks/latest/userguide/creating-access-entries.html
# groups:
#   - groupname1
#   - groupname2
