apiVersion: v1
kind: Secret
metadata:
  name: {{ template "docker-registry.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.haSharedSecret }}
  haSharedSecret: {{ .Values.secrets.haSharedSecret | b64enc | quote }}
  {{- else }}
  haSharedSecret: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  proxyUsername: {{ .Values.proxy.username | default "" | b64enc | quote }}
  proxyPassword: {{ .Values.proxy.password | default "" | b64enc | quote }}
