apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "javadoc.fullname" . }}
  labels: {{ include "javadoc.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;

      # https://github.com/jenkins-infra/helpdesk/issues/4594
      location /component/github-api {
        return 308 https://hub4j.github.io/github-api/apidocs/org.kohsuke.github.api/module-summary.html;
      }

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          autoindex on;
      }
    }
