---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap.fullname" . }}
  labels:
{{ include "ldap.labels" . | indent 4 }}
type: Opaque
data:
  ldap.admin.password: {{ .Values.ldap.admin.password | b64enc }}
