{{- if eq .Values.configuration.rsyncdDaemon "rsyncd" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rsyncd.fullname" . }}-conf
data:
  rsyncd.inc: |-
    ### /etc/rsyncd.d/rsyncd.inc: configuration file merged with /etc/rsyncd
    ### See rsyncd.conf man page for more options.
    ### See https://github.com/jenkins-infra/docker-rsyncd

    ## Read Only Service
    # Any attempted uploads will fail
    read only = true
    # Downloads will be possible if file permissions on the daemon side allow them
    write only = false
  {{- range .Values.configuration.components }}
  {{ .name }}.conf: |-
    [{{ .name }}]
    path = {{ .path }}
    comment = {{ .comment}}
  {{- end }}
{{- end }}
