{{- if and .Values.configuration.sshd .Values.configuration.sshd.hostKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rsyncd.fullname" . }}-hostkeys
  labels:
{{ include "rsyncd.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.configuration.sshd.hostKeys }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
