apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsyncd.fullname" . }}
  labels:
{{ include "rsyncd.labels" . | indent 4 }}
{{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
    {{- with .Values.service.LoadBalancerIP }}
  loadBalancerIP: {{ . }}
    {{- end }}
    {{- with .Values.service.whitelistedSources }}
  loadBalancerSourceRanges:
      {{- range . }}
    - {{ . | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  ports:
    - port: {{ include "rsyncd.service.port" . }}
      targetPort: {{ include "rsyncd.port" . }}
      protocol: TCP
      name: {{ .Values.configuration.rsyncdDaemon }}
  selector:
    app.kubernetes.io/name: {{ include "rsyncd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
