apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    {{- if .Values.ipv6PipName }}
    service.beta.kubernetes.io/azure-pip-name: {{ .Values.ipv6PipName | quote }}
    {{- end }}
    {{- if .Values.resourceGroup }}
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.resourceGroup }}
    {{- end }}
  labels:
    app.kubernetes.io/component: {{ .Values.app.component }}
    app.kubernetes.io/instance: {{ .Values.app.instance }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    # app.kubernetes.io/part-of: {{ .Release.name }}
  name: {{ .Values.app.instance }}-{{ .Values.app.name }}-{{ .Values.app.component }}-ipv6
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Values.app.instance }}
    app.kubernetes.io/component: {{ .Values.app.component }}
