image:
  repository: geoipupdates
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
# securityContext:
# Secret values, set to empty below for reference:
geoipupdate:
  dryrun: false #use boolean to set dryrun to not call geoipupdater to avoid ratelimit
  account_id: ""
  license_key: ""
  fileshare_client_id: ""
  fileshare_client_secret: ""
  fileshare_tenant_id: ""
  editions: "GeoLite2-ASN GeoLite2-City GeoLite2-Country"
  update_frequency: 24
  storage_name: ""
  storage_fileshare: ""
  cron: '0 4 * * *' # default to every day at 4AM
podSecurityContext: {}
# fsGroup: 2000
containerSecurityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
