image: ghcr.io/maxmind/geoipupdate
imagePullSecrets: []
imagePullPolicy: IfNotPresent
# securityContext:
# Secret values, set to empty below for reference:
geoipupdate:
  account_id: ""
  license_key: ""
  editions: GeoLite2-ASN GeoLite2-City GeoLite2-Country
  update_frequency: 24
podSecurityContext: {}
# fsGroup: 2000
containerSecurityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}

## Defines the geoipdata volume
## Example with a statically provisionned PVC;
# dataVolume:
#   persistentVolumeClaim:
#     claimName: existing-pvc
