# Default values for docker-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: registry
  tag: 2.8.3
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1000

port: 5000

service:
  type: ClusterIP
  port: 5000
  annotations: {}
  # foo.io/bar: "true"
  labels: {}
  # foo.io/baz: "false"

  ### TODO: to expose metrics

resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

### TODO: Datadog Integration
# datadog:
#   metricsCollection:
#     enabled: true
#   logCollection:
#     enabled: true

nodeSelector: {}
tolerations: []
affinity: {}

initContainers: []
## Init containers to add to the Deployment
# - name: init
#   image: busybox
#   command: []

configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    # headers:
    #   X-Content-Type-Options: [nosniff]
    # debug:
    #   addr: :5001
    #   prometheus:
    #     enabled: false
    #     path: /metrics
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3

# Set this to name of secret for tls certs
# tlsSecretName: registry.docker.example.com

### TODO
# secrets:
#   haSharedSecret: ""

# https://docs.docker.com/registry/recipes/mirror/
proxy:
  enabled: false
  remoteurl: https://registry-1.docker.io
  username: ""
  password: ""

persistence:
  enabled: false
  accessMode: "ReadWriteOnce"
  size: 10Gi
  # deleteEnabled: true
  # storageClass: "-"

extraEnvVars: []
## Additional ENV variables to set
# - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
#   value: "/var/lib/example"
