---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mirrorbits.fullname" . }}
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mirrorbits.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mirrorbits.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum | trunc 63 }}
    spec:
      automountServiceAccountToken: false
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
      {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
      {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: mirrorbits-config
              mountPath: /etc/mirrorbits
              readOnly: true
            - name: geoipdata
              mountPath: {{ .Values.config.geoipDatabase }}
              readOnly: true
            {{- if and .Values.config .Values.config.logs .Values.config.logs.enabled }}
            - name: logs
              mountPath: {{ .Values.config.logs.path }}
              readOnly: false
            {{- end }}
            - name: data
              mountPath: {{ .Values.config.repository }}
              readOnly: true
          livenessProbe:
            httpGet:
              path: /?mirrorstats
              port: 8080
          readinessProbe:
            httpGet:
              path: /?mirrorstats
              port: 8080
      {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: mirrorbits-config
          secret:
            secretName: {{ include "mirrorbits.config-secretname" . }}
            items:
              - key: mirrorbits.conf
                path: mirrorbits.conf
        {{- if and .Values.config .Values.config.logs .Values.config.logs.enabled }}
        - name: logs
          {{- toYaml .Values.config.logs.volume | nindent 10 }}
        {{- end }}
        - name: data
          {{- include "mirrorbits.data-volume" . | nindent 10}}
        - name: geoipdata
        {{- if .Values.geoipdata.persistentData.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "mirrorbits.geoipdata" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
