{{- if and .Values.ingress.enabled (not (dig "global" "ingress" "enabled" false .Values.AsMap)) }}
---
  {{- $fullName := include "mirrorbits.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- end }}
  {{- range $index, $addIngress := .Values.ingress.additionalIngresses }}
    {{- $ingressName := printf "%s-%d" $fullName (add $index 1) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
{{ include "mirrorbits.labels" $ | indent 4 }}
    {{- with $addIngress.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    {{- with $addIngress.className }}
  ingressClassName: {{ . }}
    {{- end }}
    {{- with $addIngress.tls }}
  tls:
      {{- range . }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  rules:
    {{- range $addIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
      {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if and .Values.cli.enabled .Values.cli.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mirrorbits.fullname" . }}-cli
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
  {{- with .Values.cli.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.cli.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
  {{- range .Values.cli.ingress.tls }}
    - hosts:
    {{- range .hosts }}
        - {{ . | quote }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  rules:
  {{- range .Values.cli.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: {{ include "mirrorbits.fullname" $ }}-cli
                port:
                  number: {{ $.Values.cli.port }}
  {{- end }}
{{- end }}
