{{ if and .Values.repository.persistentVolumeClaim.enabled (not (dig "global" "ingress" "enabled" false .Values.AsMap)) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.repository.name | default (printf "%s-binary" (include "mirrorbits.fullname" .))  }}
spec:
{{ toYaml .Values.repository.persistentVolumeClaim.spec | nindent 2 }}
{{- end }}
{{ if .Values.geoipdata.persistentData.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mirrorbits.geoipdata" . }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.geoipdata.persistentData.capacity}}
  storageClassName: {{ .Values.geoipdata.persistentData.storageClassName}}
  volumeName: {{ include "mirrorbits.geoipdata" . }}
{{- end }}
