{{ if and .Values.repository.persistentVolume.enabled (not (dig "global" "storage" "enabled" false .Values.AsMap)) -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mirrorbits.data-name" . }}
  labels:
    data: {{ include "mirrorbits.data-name" . }}
spec:
{{ toYaml .Values.repository.persistentVolume.spec | nindent 2 }}
{{- end }}
{{ if .Values.geoipdata.persistentData.enabled -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mirrorbits.geoipdata-name" . }}
  labels:
    data: {{ include "mirrorbits.geoipdata-name" . }}
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: {{ .Values.geoipdata.persistentData.capacity}}
{{- with .Values.geoipdata.persistentData.csi}}
  csi:
    {{- toYaml . | nindent 4 -}}
{{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.geoipdata.persistentData.storageClassName}}
{{- end }}
