{{- if and .Values.repository.secrets.enabled (not (dig "global" "storage" "enabled" false .Values.AsMap)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}-binary
type: Opaque
data:
  {{- range $key, $val := .Values.repository.secrets.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.config-secretname" . }}
type: Opaque
data:
  "mirrorbits.conf": {{ include "mirrorbits.configmap" . | b64enc }}
