---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mirrorbits.fullname" . }}
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mirrorbits.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.cli.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mirrorbits.fullname" . }}-cli
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
{{- with .Values.cli.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.cli.service.type }}
  ports:
    - port: {{ .Values.cli.port }}
      targetPort: {{ .Values.cli.port }}
      protocol: TCP
      name: cli
  selector:
    app.kubernetes.io/name: {{ include "mirrorbits.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
