apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
{{ include "geoipupdate.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.geoipupdate.cron }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: geoipupdate
              image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              {{- with .Values.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: tmpdir
                  mountPath: /tmp
                  readOnly: false
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
                {{- with .Values.geoipupdate.editions }}
                - name: GEOIPUPDATE_EDITION_IDS
                  value: {{ . }}
                {{- end }}
                {{- with .Values.geoipupdate.update_frequency }}
                - name: GEOIPUPDATE_FREQUENCY
                  value: {{ . | quote }}
                {{- end }}
                {{- with .Values.geoipupdate.storage_name }}
                - name: STORAGE_NAME
                  value: {{ . }}
                {{- end }}
                {{- with .Values.geoipupdate.storage_fileshare }}
                - name: STORAGE_FILESHARE
                  value: {{ . }}
                {{- end }}
              envFrom:
              - secretRef:
                  name: {{ include "geoipupdate.fullname" . }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: tmpdir
              emptyDir:
                medium: "Memory"
