apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
{{ include "geoipupdate.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
{{ include "geoipupdate.labels" . | indent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["pods"]
    resourceNames: [{{ include "geoipupdate.fullname" . }}]
    verbs: ["get", "read", "list", "watch", "create", "patch", "replace", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "geoipupdate.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "geoipupdate.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "geoipupdate.fullname" . }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
{{ include "geoipupdate.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.geoipupdate.cron }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "geoipupdate.fullname" . }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: tmpdir
                  mountPath: /tmp
                  readOnly: false
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                {{- with .Values.geoipupdate.dryrun }}
                - name: GEOIPUPDATE_DRYRUN
                  value: DRYRUN
                {{- end }}
                {{- with .Values.geoipupdate.editions }}
                - name: GEOIPUPDATE_EDITION_IDS
                  value: {{ . }}
                {{- end }}
                {{- with .Values.geoipupdate.update_frequency }}
                - name: GEOIPUPDATE_FREQUENCY
                  value: {{ . | quote }}
                {{- end }}
                {{- with .Values.geoipupdate.storage_name }}
                - name: STORAGE_NAME
                  value: {{ . }}
                {{- end }}
                {{- with .Values.geoipupdate.storage_fileshare }}
                - name: STORAGE_FILESHARE
                  value: {{ . }}
                {{- end }}
              envFrom:
              - secretRef:
                  name: {{ include "geoipupdate.fullname" . }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: tmpdir
              emptyDir:
                medium: "Memory"
