---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
{{ include "geoipupdate.labels" . | indent 4 }}
spec:
  replicas: 1 # Do not scale up or you will run in trouble
  selector:
    matchLabels:
{{ include "geoipupdate.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "geoipupdate.selectorLabels" . | indent 8 }}
    spec:
      automountServiceAccountToken: false
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: geoipupdate
          image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
    {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
    {{- end }}
          volumeMounts:
            - name: geoipdata
              mountPath: /usr/share/GeoIP
              readOnly: false
            - name: tmpdir
              mountPath: /tmp
              readOnly: false
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GEOIPUPDATE_EDITION_IDS
              value: {{ .Values.geoipupdate.editions }}
            - name: GEOIPUPDATE_FREQUENCY
              value: {{ .Values.geoipupdate.update_frequency | quote }}
          envFrom:
          - secretRef:
              name: {{ include "geoipupdate.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: geoipdata
    {{- if .Values.dataVolume }}
      {{- toYaml .Values.dataVolume | nindent 10 }}
    {{- else }}
          emptyDir: {}
    {{- end }}
        - name: tmpdir
          emptyDir:
            medium: "Memory"
...
