apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
{{ include "geoipupdate.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
{{ include "geoipupdate.labels" . | indent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["pods"]
    resourceNames: [{{ include "geoipupdate.fullname" . }}]
    verbs: ["get", "read", "list", "watch", "create", "patch", "replace", "delete"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["updates-jenkins-io", "get-jenkins-io"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "geoipupdate.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "geoipupdate.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "geoipupdate.fullname" . }}
