{{- if and .Values.geoipupdate.account_id .Values.geoipupdate.license_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoipupdate.fullname" . }}
type: Opaque
data:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.geoipupdate.account_id | b64enc }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.geoipupdate.license_key | b64enc }}
  JENKINS_INFRA_FILESHARE_CLIENT_ID: {{ .Values.geoipupdate.fileshare_client_id | b64enc }}
  JENKINS_INFRA_FILESHARE_CLIENT_SECRET: {{ .Values.geoipupdate.fileshare_client_secret | b64enc }}
  JENKINS_INFRA_FILESHARE_TENANT_ID: {{ .Values.geoipupdate.fileshare_tenant_id | b64enc }}
{{- end }}
