{{- if and .Values.geoipupdate.account_id .Values.geoipupdate.license_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoipupdate.fullname" . }}
type: Opaque
data:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.geoipupdate.account_id | b64enc }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.geoipupdate.license_key | b64enc }}
{{- end }}
