apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artifact-caching-proxy.fullname" . }}
  labels:
    {{- include "artifact-caching-proxy.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "artifact-caching-proxy.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "artifact-caching-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/default-config: {{ include (print $.Template.BasePath "/nginx-default-configmap.yaml") . | sha256sum }}
        checksum/proxy-config: {{ include (print $.Template.BasePath "/nginx-proxy-configmap.yaml") . | sha256sum }}
        {{- if .Values.datadog.metricsCollection.enabled }}
        # Nginx Metrics collection with Datadog:
        # - https://docs.datadoghq.com/integrations/nginx/?tab=kubernetes
        # - https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=kubernetesadv2#configuration
        #   1. With 'ad.datadoghq.com/xxx.checks' , the 'xxx' must be the name of the pod's container name
        #   2. The doc. mentions "<INTEGRATION NAME>" which is "nginx" in our case (as the name of datadog integration system)
        ad.datadoghq.com/{{ .Chart.Name }}.checks: |
          {
            "nginx": {
              "init_config": {},
              "instances": [
                {
                  "nginx_status_url":"http://%%host%%:{{ .Values.service.statusPort }}/nginx_status/"
                }
              ]
            }
          }
        {{- end }}
        {{- if .Values.datadog.logCollection.enabled }}
        # Nginx Log collection with Datadog:
        # - https://docs.datadoghq.com/integrations/nginx/?tab=kubernetes#log-collection
        # - https://docs.datadoghq.com/containers/kubernetes/log/?tab=kubernetes#configuration
        #   1. With 'ad.datadoghq.com/xxx.logs' , the 'xxx' must be the name of the pod's container name
        ad.datadoghq.com/{{ .Chart.Name }}.logs: '[{"source":"nginx","service":"{{ .Chart.Name }}"}]'
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "artifact-caching-proxy.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.initContainers.enabled }}
      initContainers:
      - name: permission-fix
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ['chown', '-R', 'nginx:nginx', '{{ .Values.cache.path }}']
        volumeMounts:
          - mountPath: {{ .Values.cache.path }}
            name: nginx-cache
      {{- end}}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
        envFrom:
          {{- toYaml .Values.envFrom | nindent 10 }}
        ports:
          - name: http
            containerPort:  {{ .Values.service.port }}
            protocol: TCP
          - name: status
            containerPort:  {{ .Values.service.statusPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.ingress.healthPath }}
            port: http
        readinessProbe:
          httpGet:
            path: {{ .Values.ingress.healthPath }}
            port: http
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: nginx-default-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-proxy-config
          mountPath: /etc/nginx/conf.d/
        - name: nginx-tmp
          mountPath: /var/tmp/
        - name: nginx-cache
          mountPath: {{ .Values.cache.path }}
      volumes:
      - name: nginx-default-config
        configMap:
          name: {{ include "artifact-caching-proxy.fullname" . }}-default-configmap
      - name: nginx-proxy-config
        configMap:
          name: {{ include "artifact-caching-proxy.fullname" . }}-proxy-configmap
      - name: nginx-tmp
        emptyDir: {}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.claimPrefix }}
    spec:
      {{- with .Values.persistence.storageClass }}
      storageClassName: {{ . }}
      {{- end }}
      accessModes:
      - {{ .Values.persistence.accessMode }}
      resources:
        requests:
          storage: "{{ .Values.persistence.size }}Gi"
  {{- else }}
      - name: nginx-cache
        emptyDir: {}
  {{- end }}
